#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright (c) 2012 Martin Ueding <dev@martin-ueding.de>

import optparse
import os

patterns = {
    "xls": "Microsoft Excel",
    "key": "Apple Keynote",
    "numbers": "Apple Numbers",
    "pages": "Apple Pages",
    "nb": "Mathematica Notebook",
    "mw": "Maple Worksheet"
}

def main():
    parser = optparse.OptionParser(usage="legacy paths...", description="Checks for proprietary or legacy file formats that do not have a PDF exported.")
    parser.add_option("--suffix", dest="suffix", default="pdf", help="Additional suffix to check for [default %default]")

    (options, args) = parser.parse_args()
    del parser

    options.suffix = options.suffix.lower()

    for arg in args:
        os.path.walk(arg, checkfolder, options)

def checkfolder(options, dirname, names):
    for name in names:
        for pattern in patterns:
            if name.lower().endswith("."+pattern):
                pdffile = dirname+"/"+name+"."+options.suffix
                if not os.path.isfile(pdffile):
                    # Check whether the file has the same name, just a PDF extension.
                    alt_pdffile = dirname+"/"+os.path.splitext(name)[0]+"."+options.suffix
                    if os.path.isfile(alt_pdffile):
                        os.rename(alt_pdffile, pdffile)
                    else:
                        print dirname+"/"+name


if __name__ == "__main__":
	main()
